# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_CPU_RK3588) += rk3588-lubancat-rk_series.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588-lubancat-5.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588-lubancat-5io.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588s-lubancat-4.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588s-lubancat-4-v1.dtb

subdir-y	:= $(dts-dirs) overlay

