# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_CPU_RK3528) += rk3528-lubancat-generic.dtb
dtb-$(CONFIG_CPU_RK3528) += rk3528-lubancat-q1.dtb

dtb-$(CONFIG_CPU_RK3562) += rk3562-lubancat-generic.dtb
dtb-$(CONFIG_CPU_RK3562) += rk3562-lubancat-1hs.dtb

dtb-$(CONFIG_CPU_RK3588) += rk3588-lubancat-generic.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588-lubancat-5.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588-lubancat-5io.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588s-lubancat-4.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588s-lubancat-4-v1.dtb

subdir-y	:= $(dts-dirs) overlay

